## Filebeat configuration
## https://github.com/elastic/beats/blob/main/deploy/docker/filebeat.docker.yml
#

name: filebeat

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    # The Docker autodiscover provider automatically retrieves logs from Docker
    # containers as they start and stop.
    - type: docker
      templates:
        - condition:
            contains:
              docker.container.image: custom_dev_for_kl-app
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.container.id}/*-json.log

processors:
  - decode_json_fields:
      fields: [ "message" ]
      process_array: false
      max_depth: 2
      target: ""
      overwrite_keys: false
      add_error_key: true
  - drop_fields:
      fields: [ "docker", "@metadata","agent","host","input","container","log","message" ]


#monitoring:
#  enabled: true
#  elasticsearch:
#    username: beats_system
#    password: ${BEATS_SYSTEM_PASSWORD}

#output.elasticsearch:
#  hosts: [ http://elasticsearch:9200 ]
#  username: filebeat_internal
#  password: ${FILEBEAT_INTERNAL_PASSWORD}

output.file:
  path: "/tmp/filebeat"
  filename: filebeat
  rotate_every_kb: 10000
  number_of_files: 1024
  permissions: 0600
  rotate_on_startup: true

## HTTP endpoint for health checking
## https://www.elastic.co/guide/en/beats/filebeat/current/http-endpoint.html
#

http:
  enabled: true
  host: 0.0.0.0
